-- CONSULTAS PARA CARGAR EN TABLA PERSONA
INSERT INTO PERSONA(NOMBRES, APELLIDOS) VALUES('Jennifer Maria', 'Villada Guiterrez');
INSERT INTO PERSONA(NOMBRES, APELLIDOS) VALUES('Bridgette Camila', 'Gomez Faro');
INSERT INTO PERSONA(NOMBRES, APELLIDOS) VALUES('Sofia Lupe', 'Aragon Pleitzel');
INSERT INTO PERSONA(NOMBRES, APELLIDOS) VALUES('Paulina Ximena', 'Ramirez Valerio');
INSERT INTO PERSONA(NOMBRES, APELLIDOS) VALUES('Karina Paola', 'Amaya Valle');
INSERT INTO PERSONA(NOMBRES, APELLIDOS) VALUES('Laura Adriana', 'Cortez Duarte');

-- CONSULTAS PARA CARGAR EN TABLA PRODUCTOS
INSERT INTO PRODUCTO(NOMBRE, MARCA) VALUES('7UP', 'Pepsi');
INSERT INTO PRODUCTO(NOMBRE, MARCA) VALUES('Chocolate Blanco', 'Hersheys');
INSERT INTO PRODUCTO(NOMBRE, MARCA) VALUES('Monopoly', 'Hasbro');
INSERT INTO PRODUCTO(NOMBRE, MARCA) VALUES('Casco de realidad virtual Oculus', 'HTC');
INSERT INTO PRODUCTO(NOMBRE, MARCA) VALUES('PlayStation Store Gift Card', 'Sony');
INSERT INTO PRODUCTO(NOMBRE, MARCA) VALUES('Cubo Rubik', 'Hasbro');
INSERT INTO PRODUCTO(NOMBRE, MARCA) VALUES('Doritos', 'Frito-lay');

-- EJEMPLO DE VENTA REALIZADA
-- INSERT INTO VENTA (ID_VENTA, FECHA, IMPORTE, ID_PERSONA) VALUES(1, '2019-06-19 05:00:00', 59.77, 1);
INSERT INTO VENTA (FECHA, IMPORTE, ID_PERSONA) VALUES('2019-06-19 05:00:00', 59.77, 1);

-- EJEMPLO DE DETALLE VENTA
INSERT INTO DETALLE_VENTA(CANTIDAD, ID_PRODUCTO, ID_VENTA) VALUES (1, 3, 1);
INSERT INTO DETALLE_VENTA(CANTIDAD, ID_PRODUCTO, ID_VENTA) VALUES (8, 5, 1);
INSERT INTO DETALLE_VENTA(CANTIDAD, ID_PRODUCTO, ID_VENTA) VALUES (5, 1, 1);
